// Generated by CoffeeScript 1.8.0
(function() {
  var e, makeHeadingBetter, makeTextBetter, _i, _len, _ref;

  makeTextBetter = function(text) {
    var bettertext, bracketCount, case_phase, char, index, symbols, _i, _j, _len;
    symbols = text.split("");
    bettertext = "";
    for (index = _i = 0, _len = symbols.length; _i < _len; index = ++_i) {
      char = symbols[index];
      case_phase = Math.random();
      if (case_phase > 0.5) {
        char = char.toLowerCase();
      } else {
        char = char.toUpperCase();
      }
      bettertext += char;
    }
    bracketCount = Math.random() * 100;
    for (_j = 1; 1 <= bracketCount ? _j <= bracketCount : _j >= bracketCount; 1 <= bracketCount ? _j++ : _j--) {
      bettertext += ")";
    }
    return bettertext;
  };

  makeHeadingBetter = function(text) {
    var _i, _j, _ref, _ref1;
    if (text.split("").pop() === "!") {
      text += " !";
      for (_i = 1, _ref = Math.random() * 50; 1 <= _ref ? _i <= _ref : _i >= _ref; 1 <= _ref ? _i++ : _i--) {
        text += "!";
      }
    } else {
      text += " :";
      for (_j = 1, _ref1 = Math.random() * 20; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; 1 <= _ref1 ? _j++ : _j--) {
        text += "*";
      }
    }
    return text;
  };

  document.body.style.backgroundColor = "";

  document.body.style.backgroundColor = "00ff00";

  document.body.style.backgroundImage = "url(http://carrymove.com/betterlook/rose.png)";

  document.body.style.backgroundRepeat = "repeat";

  _ref = document.body.getElementsByTagName("*");
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    e = _ref[_i];
    switch (e.tagName) {
      case "DIV":
        e.style.backgroundColor = "ff00ff";
        break;
      case "H1":
      case "H2":
      case "H3":
      case "H4":
      case "H5":
      case "H6":
        e.innerText = makeHeadingBetter(e.innerText);
        e.style.fontFamily = "Monotype Corsiva";
        break;
      case "P":
        e.innerText = makeTextBetter(e.innerText);
        e.style.color = "ff0000";
        break;
      default:
        e.style.backgroundColor = "ff00ff";
    }
    e.style.fontFamily = "Comic Sans MS";
  }

}).call(this);

//# sourceMappingURL=makestuff.js.map
